theme: minima
markdown: kramdown
title: Estándares Empíricos
description: Estándares Empíricos para realizar y evaluar investigaciones en Ingeniería del Software
header_pages:
  - tab_01_about.md
  - tab_02_tools.md
  - tab_03_standards.md
  - tab_04_supplements.md
  - tab_05_faq.md
  - tab_06_people.md
collections:
  team:
    output: true
